#pragma once


namespace Client
{
	enum LEVEL
	{
		LEVEL_STATIC,
		LEVEL_LOADING,
		LEVEL_LOGO,
		//LEVEL_MENU,
		LEVEL_GAMEPLAY,
		LEVEL_EDIT_ANIM,

		LEVEL_EDIT_UI,

		LEVEL_END
	};


	enum TICK_GROUP
	{
		TG_DEFAULT,

		TG_TERRAIN,
		TG_ENEMY,
		TG_PLAYER,
		TG_WEAPON,
		TG_MAP,
		TG_EFFECT,
		TG_NPC,
		TG_UI,
		TG_UI_MENU,
		TG_UI_TALK,
		TG_UI_ALERT,
		TG_UI_ORDERLIST,
		TG_UI_PLACENAME,

		TG_END
	};

	enum LATETICK_GROUP
	{
		LTG_DEFAULT,

		LTG_TERRAIN,
		LTG_ENEMY,
		LTG_PLAYER,
		LTG_WEAPON,
		LTG_MAP,
		LTG_EFFECT,
		LTG_NPC,
		LTG_UI,
		LTG_UI_MENU,
		LTG_UI_TALK,
		LTG_UI_ALERT,
		LTG_UI_ORDERLIST,
		LTG_UI_PLACENAME,

		LTG_END
	};

	enum ANIM_GROUP
	{
		ANIM_DEFAULT,

		ANIM_PLAYER_FEMALE,
		ANIM_PLAYER_MALE,

		ANIM_END
	};

	enum COLLIDER_TYPE
	{
		COL_PLAYER_ATTACK = 10,
		COL_PLAYER_BODY,
		COL_PLAYER_UIINTRC,
		COL_PLAYER_VOLUME,
		COL_PLAYER_ATTACK_RANGE,
		COL_PLAYER_EVASION,

		COL_ENEMY_ATTACK,
		COL_ENEMY_HITRANGE,
		COL_ENEMY_BOSS_VOLUME,
		COL_ENEMY_VOLUME,
		COL_ENEMY_ATTACKRANGE,
		COL_ENEMY_CHASERANGE,
		COL_ENEMY_SAFERANGE,

		COL_TRIGGER,
		COL_TRIGGER_PORTAL,

		COL_ITEM,

		COL_NPC,

		COL_EQUIPMENT,

		COL_REGION,

		COL_MINIGAME,

		COL_TYPE_END
	};

#pragma region Component

	enum COMPONENT
	{
		RENDERER,
		VIBUFFER,
		TRANSFORM,
		SHADER,
		TEXTURE,
		MODEL_STATIC,
		MODEL_DYNAMIC,
		COLLIDER,
		STATE_HANDLER,
		NAVIGATION,
		MODEL_STATIC_INSTANCE,
		MODEL_DYNAMIC_INSTANCE,

		COMPONENT_END
	};

	enum COLLIDER
	{
		COLLIDER_AABB = 10,
		COLLIDER_OBB,
		COLLIDER_SPHERE,

		COLLIDER_END
	};

	enum VIBUFFER
	{
		BUFFER_CUBE = 1,
		BUFFER_RECT,
		BUFFER_TERRAIN,
		BUFFER_RECT_INSTANCE,
		BUFFER_POINT_INSTANCE,
		BUFFER_TERRAIN_CUSTOM,
		BUFFER_NAVI,
		BUFFER_TRAIL,
		BUFFER_TERRAIN_TESS,
		BUFFER_TERRAIN_TESS_CUSTOM,
		BUFFER_CLOUD_INSTANCE,

		BUFFER_END
	};

	enum SHADER
	{
		SHADER_VTXTEX = 10,
		SHADER_VTXCOLOR,
		SHADER_VTXNORTEX,
		SHADER_VTXCUBETEX,
		SHADER_VTXANIM,
		SHADER_VTXMODEL,
		SHADER_VTXTEXUI,
		SHADER_VTXRECTINSTANCE,
		SHADER_VTXPOINTINSTANCE,
		SHADER_VTXMODELEFFECT,
		SHADER_VTXANIMINSTANCE,
		SHADER_VTXMODELINSTANCE,
		SHADER_VTXTEXWATER,
		SHADER_DEPTH,

		SHADER_END
	};

	enum TEXTURE
	{
		TEXTURE_DEFAULT = 10,
		TEXTURE_TERRAIN,
		TEXTURE_SKY,
		TEXTURE_LOGO,
		TEXTURE_BACKGROUND,
		TEXTURE_FLITER,
		TEXTURE_BRUSH,
		TEXTURE_ERROR,
		TEXTURE_CURSOR,
		TEXTURE_NOISE,
		TEXTURE_UI,
		TEXTURE_EFFECT,
		TEXTURE_WATER,
		TEXTURE_NORMAL,
		TEXTURE_CLOUD,

		TEXTURE_END
	};

	enum TEXTURE_EFFECT
	{
		TEXTURE_EFFECT_MASK = 10,
		TEXTURE_EFFECT_NOISE,

		TEXTURE_EFFECT_END
	};

	enum TEXTURE_UI
	{
		TEXTURE_UI_CURSOR = 10,
		TEXTURE_UI_LOADING_SCREEN,
		TEXTURE_UI_LOADING_BAR,
		TEXTURE_UI_LOADING_ANIM,
		TEXTURE_UI_LOGO,
		TEXTURE_UI_SHORTKEY,
		TEXTURE_UI_MAIN,
		TEXTURE_UI_MENU,
		TEXTURE_UI_PLAYER_STATUS,
		TEXTURE_UI_SKILL,
		TEXTURE_UI_INVENTORY,
		TEXTURE_UI_FOOD_INVEN,
		TEXTURE_UI_SKILL_SLOTICON,
		TEXTURE_UI_WEAPON_SLOTICON,
		TEXTURE_UI_ENEMY_BLOOD,
		TEXTURE_UI_ENEMY_NAME,
		TEXTURE_UI_BOSS_BLOOD,
		TEXTURE_UI_BOSS_NAME,
		TEXTURE_UI_ENEMY_INDICATOR,
		TEXTURE_UI_DAMAGE_NUMBER,
		TEXTURE_UI_WINDOW,
		TEXTURE_UI_HAND_ANIM,
		TEXTURE_UI_ITEM,
		TEXTURE_UI_FOOD_ICON,
		TEXTURE_UI_ITEM_NUM,
		TEXTURE_UI_QUEST_MARK,
		TEXTURE_UI_ENEMY_RANK,
		TEXTURE_UI_2GUN_CROSSHAIR,
		TEXTURE_UI_TALK_ANIM,
		TEXTURE_UI_ALERT_WINDOW,
		TEXTURE_UI_INGREDIENT,
		TEXTURE_UI_TALK_WINDOW,
		TEXTURE_UI_PROCEEDING,
		TEXTURE_UI_PLACEMARK,
		TEXTURE_UI_QUEST_NOTICE,
		TEXTURE_UI_ATTACK_TARGET,
		TEXTURE_UI_ENEMY_ATTACK,
		TEXTURE_UI_ITEM_DETAIL,
		TEXTURE_UI_COOK_ICON,
		TEXTURE_UI_COOK_DETAIL,
		TEXTURE_UI_COOK_INGRD_NUM,
		TEXTURE_UI_EQUIP_ICON,
		TEXTURE_UI_EQUIP_WEAPON,
		TEXTURE_UI_EQUIP_DETAIL,
		TEXTURE_UI_COOK_PROGRESS,
		TEXTURE_UI_ORDER_ICON,
		TEXTURE_UI_ORDER_ANIM,
		TEXTURE_UI_ORDER_ITEM,
		TEXTURE_UI_ORDER_RESULT,
		TEXTURE_UI_ORDER_ITEMNAME,
		TEXTURE_UI_ORDER_TENRESULT,
		TEXTURE_UI_PLACENAME,
		TEXTURE_UI_ENERGY_GEAR,
		TEXTURE_UI_MINIMAP,
		TEXTURE_UI_DIST_NUM,
		TEXTURE_UI_QUEST_COMPLETE,
		TEXTURE_UI_MINIGAME_START,
		TEXTURE_UI_MINIGAME_ICON,
		TEXTURE_UI_MINIGAME_EXPLAIN,
		TEXTURE_UI_MINIGAME_GAIN,
		TEXTURE_UI_MINIGAME_RESULT,
		TEXTURE_UI_CRYSTAL_BLOOD,

		TEXTURE_UI_END
	};

	enum TEXTURETYPE
	{
		TYPE_DIFFUSE = 10,
		TYPE_FILTER,
		TYPE_BRUSH,
		TYPE_NORMAL,

		TYPE_END
	};

	enum MODEL_STATIC
	{
		STATIC = 10,
		MODEL_TILE,
		MODEL_TREE,
		MODEL_ROCK,
		MODEL_GRASS,

		MODEL_EFFECT,
		MODEL_STAIR,
		MODEL_STRUCTS,
		MODEL_WEAPON,
		MODEL_BULLET,
		MODEL_TRIGGER,
		MODEL_ITEM,
		MDOEL_GRAY_ROCK,
		MODEL_TESTPLAYER,
		MODEL_GRASS_DESERT,
		MODEL_STRUCTS_DESERT,
		MODEL_ROCK_ALL,
		MODEL_GRASSMESH,
		MODEL_ROOM,
		MODEL_EQUIPMENT,
		MODEL_STRUCTS_ALL,
		MODEL_SHELF_ITEM,
		MODEL_COIN,
		MODEL_RING,

		STATIC_END
	};

	enum MODEL_DYNAMIC
	{
		DYNAMIC = 10,
		MODEL_PLAYER,
		MODEL_NPC,
		MODEL_ENEMY,
		MODEL_ENEMY_BOSS,
		MODEL_ANIM_WEAPON,
		MODEL_TEST,

		DYNAMIC_END
	};

	enum MODEL_ENEMY_BOSS
	{
		MODEL_ENEMY_BOSS_FRANKEN = 10,
		MODEL_ENEMY_BOSS_FROST_DRAGON,
		MODEL_ENEMY_BOSS_VULCANUS,
		MODEL_ENEMY_BOSS_ANGEL,
		MODEL_ENEMY_BOSS_SEVEC,
		MODEL_ENEMY_BOSS_FROST_MECA,
		MODEL_ENEMY_BOSS_NEMESIS,
		MODEL_ENEMY_BOSS_RUDOLF,
		MODEL_ENEMY_BOSS_WEAVER,
		MODEL_ENEMY_BOSS_ROBELLA,
		MODEL_ENEMY_BOSS_LEVIATHAN_40,
		MODEL_ENEMY_BOSS_LEVIATHAN_90,

		MODEL_ENEMY_BOSS_END
	};

	enum MODEL_BULLET
	{
		MODEL_ENEMY_BULLET_DRAGON = 10,
		MODEL_ENEMY_BULLET_NORMAL_0,
		MODEL_ENEMY_BULLET_NORMAL_1,
		MODEL_ENEMY_BULLET_NORMAL_2,
		MODEL_ENEMY_BULLET_NORMAL_3,
		MODEL_ENEMY_BULLET_LASER,

		MODEL_ENEMY_BULLET_ARROW,


		MODEL_ENEMY_BULLET_END
	};

	enum MODEL_PLAYER
	{
		//Female
		MODEL_PLAYER_FEMAIL_01 = 10,
		MODEL_PLAYER_FEMAIL_02,
		MODEL_PLAYER_FEMAIL_03,
		MODEL_PLAYER_FEMAIL_04,
		MODEL_PLAYER_FEMAIL_05,
		MODEL_PLAYER_FEMAIL_06,
		MODEL_PLAYER_FEMAIL_07,
		MODEL_PLAYER_FEMAIL_08,
		MODEL_PLAYER_FEMAIL_09,
		MODEL_PLAYER_FEMAIL_10,
		MODEL_PLAYER_FEMAIL_11,
		MODEL_PLAYER_FEMAIL_12,
		MODEL_PLAYER_FEMAIL_13,
		MODEL_PLAYER_FEMAIL_14,
		MODEL_PLAYER_FEMAIL_15,

		//male
		MODEL_PLAYER_MAIL_01,
		MODEL_PLAYER_MAIL_02,
		MODEL_PLAYER_MAIL_03,
		MODEL_PLAYER_MAIL_04,
		MODEL_PLAYER_MAIL_05,
		MODEL_PLAYER_MAIL_06,
		MODEL_PLAYER_MAIL_07,
		MODEL_PLAYER_MAIL_08,
		MODEL_PLAYER_MAIL_09,
		MODEL_PLAYER_MAIL_10,
		MODEL_PLAYER_MAIL_11,
		MODEL_PLAYER_MAIL_12,
		MODEL_PLAYER_MAIL_13,
		MODEL_PLAYER_MAIL_14,
		MODEL_PLAYER_MAIL_15,

		MODEL_PLAYER_END
	};

	enum MODEL_WEAPON
	{
		MODEL_WEAPON_DEFAULT = 10,
		MODEL_WEAPON_SWORD,
		MODEL_WEAPON_2GUN,
		MODEL_WEAPON_SHIELD,
		MODEL_WEAPON_AXE,
		MODEL_WEAPON_SPEAR,
		MODEL_WEAPON_CUBE_L,
		MODEL_WEAPON_CUBE_R,

		MODEL_MOBILITY_GLIDER,
		MODEL_MOBILITY_MOTORCYCLE,

		/*Enemy_Weapon*/
		MODEL_ENEMY_WEAPON_STIC,
		MODEL_ENEMY_WEAPON_BOW,
		MODEL_ENEMY_WEAPON_WASTEBASKET,
		MODEL_ENEMY_WEAPON_HAMMER,


		MODEL_WEAPON_END
	};

	enum MODEL_TRIGGER
	{
		TRIGGER_DEFAULT = 10,
		TRIGGER_DRAGON,

		TRIGGER_END,
	};

	enum MODEL_NPC
	{
		MODEL_NPC_DEFAULT = 10,
		MODEL_SHIRLEY,
		MODEL_COOKER,

		MODEL_NPC_END
	};

#pragma endregion Component


	enum OBJECT
	{
		BACKGROUND = 10,
		CAMERA,
		PLAYER,
		ENEMY,
		NPC,
		EFFECT,
		SKY,
		LOGO,
		UI,
		MAP,
		MODELTEST,
		WEAPON,
		UISOLID,
		QUEST,
		ORDER,

		OBJECT_END
	};

	enum PLAYER
	{
		PLAYER_DEFAULT = 10,
		PLAYER_MALE,
		PLAYER_FEMALE,
		PLAYER_TESTOBJ,

		PLAYER_END
	};

	enum ENEMY
	{
		ENEMY_NORMAL = 10,
		ENEMY_BOSS,
		ENEMY_BULLET,

		ENEMY_END
	};

	enum NPC
	{
		NPC_DEFAULT = 10,
		NPC_SHIRLEY,
		NPC_COOKER,

		NPC_END
	};

	enum UI
	{
		UI_CURSOR = 10,
		UI_LOADING_SCREEN,
		UI_LOADING_BAR,
		UI_LOADING_ANIM,
		UI_LOGO,
		UI_LOGO_BACK,
		UI_LOGO_START,
		UI_SHORTKEY,
		UI_MENU_BACK,
		UI_MENU_BUTTON,
		UI_MAIN_ICON,
		UI_DASH_BAR,
		UI_PLAYER_HP_BAR,
		UI_PLAYER_HP_BACK,
		UI_MAIN_BUTTON,
		UI_SKILL_GAUGE,
		UI_SKILL_ENABLE,
		UI_STAMINA_BACK,
		UI_STAMINA_BAR,
		UI_INVEN_ICON,
		UI_INVEN_BUTTON,
		UI_WEAPON_SKILL,
		UI_SKILL_R,
		UI_SKILL_L,
		UI_SKILL_M,
		UI_FOOD_WINDOW,
		UI_BOSS_HP_BAR,
		UI_BOSS_NAME,
		UI_BOSS_HP_BACK,
		UI_DAMAGE_NUM,
		UI_GUIDE_WINDOW,
		UI_GUIDE_HAND_ANIM,
		UI_ITEM,
		UI_FOOD_ICON,
		UI_CURFOOD_ICON,
		UI_FOOD_NUM,
		UI_CURFOOD_NUM,
		UI_ATTACKED_NUM,
		UI_HEAL_NUM,
		UI_ITEM_NUM,
		UI_BOSS_HP_LERP,
		UI_QUEST_MARK,
		UI_GUN_CROSSHAIR,
		UI_GUIDE_TALK_ANIM,
		UI_ALERT_WINDOW,
		UI_ALERT_ICON,
		UI_TALK_WINDOW,
		UI_PROCEEDING,
		UI_PLACEMARK,
		UI_DIST_NUM,
		UI_QUEST_NOTICE,
		UI_ATTACK_TARGET,
		UI_ITEM_DETAIL,
		UI_COOK_BUTTON,
		UI_COOK_ICON,
		UI_COOK_INGREDIENT,
		UI_COOK_FOOD,
		UI_COOK_FOODSELECT,
		UI_COOK_DETAIL,
		UI_COOK_INGRDNUM,
		UI_EQUIP_BUTTON,
		UI_EQUIP_WEAPON_M,
		UI_EQUIP_WEAPON_L,
		UI_EQUIP_WEAPON_R,
		UI_EQUIP_ICON,
		UI_EQUIP_DETAIL,
		UI_COOK_GAUGEBAR,
		UI_COOK_GAUGENUM,
		UI_SKILL_TIME,
		UI_EQUIP_REMOVE,
		UI_ORDER_ICON,
		UI_ORDER_BUTTON,
		UI_ORDER_ANIM,
		UI_ORDER_ITEM,
		UI_ORDER_RESULT,
		UI_ORDER_RESULTBUTTON,
		UI_ORDER_ITEMNAME,
		UI_ORDER_TENRESULT,
		UI_PLACENAME,
		UI_ENERGY_GEAR,
		UI_MINIMAP_ARROW,
		UI_MINIMAP,
		UI_QUEST_COMPLETE,
		UI_MINIGAME_START,
		UI_MINIGAME_NOTICE,
		UI_MINIGAME_EXPLAIN,
		UI_MINIGAME_GAIN,
		UI_MINIGAME_RESULT,
		UI_CRYSTAL_HP_BAR,
		UI_FIN,

		UI_END
	};

	enum UISOLID
	{
		UISOLID_ENEMY_HP_BAR = 10,
		UISOLID_ENEMY_NAME,
		UISOLID_ENEMY_INDICATOR,
		UISOLID_ENEMY_RANK,
		UISOLID_ENEMY_ATTACK,

		UISOLID_END
	};

	enum EFFECT
	{
		EFFECT_MESH = 10,
		EFFECT_PARTICLE_RECT,
		EFFECT_PARTICLE_POINT,
		EFFECT_TRAIL,

		EFFECT_END
	};

	enum MAP
	{
		MAP_TILE = 10,
		MAP_ROCK,
		MAP_TREE,
		MAP_GRASS,
		MAP_INSTANCE,
		MAP_TERRAIN,
		MAP_STAIR,
		MAP_STRUCTS,
		MAP_WATER,
		MAP_NAVI,
		MAP_TRIGGER,
		MAP_ITEM,
		MAP_GRAY_ROCK,
		MAP_TEST_PLAYER,
		MAP_GRASS_DESERT,
		MAP_STRUCTS_DESERT,
		MAP_ROCK_ALL,
		MAP_GRASSMESH,
		MAP_ROOM,
		MAP_EQUIPMENT,
		MAP_WATER_BASE,
		MAP_PORTAL,
		MAP_STRUCTS_ALL,
		MAP_SHELF_ITEM,
		MAP_CLOUD,
		MAP_CLOUD_SKY,
		MAP_REGION,
		MAP_COIN,
		MAP_RING,

		MAP_END
	};

	enum CAMERA_TYPE
	{
		CAMERA_FREE = 10,
		CAMERA_TARGET_MATRIX,
		CAMERA_TARGET_POSITION,
		CAMERA_TARGET_POSITION_LERP,
		CAMERA_FIXED,
		CAMERA_ACTION,

		CAMERA_FIXED0 = 20,



		CAMERA_END,
	};


	enum COLLIDERLAYER
	{
		COLLAYER_DYNAMIC,
		COLLAYER_BUTTON,
		COLLAYER_ZONE,
		COLLAYER_PLAYER,

		COLLAYER_END
	};



	enum STATE_TYPE
	{
		STATE_DEFAULT = 10,

#pragma region Normal
		// Player
		STATE_PLAYER_IDLE,
		STATE_PLAYER_HAND_IDLE,
		STATE_PLAYER_WALK,
		STATE_PLAYER_RUN,
		STATE_PLAYER_JUMP_A,
		STATE_PLAYER_JUMP_B,
		STATE_PLAYER_JUMP_END,
		STATE_PLAYER_JUMP_FALL,

		STATE_PLAYER_ROLL_FORWORD,
		STATE_PLAYER_ROLL_FORWORD_AIR,
		STATE_PLAYER_ROLL_FORWORD_END,
		STATE_PLAYER_ROLL_BACK,
		STATE_PLAYER_ROLL_BACK_AIR,

		STATE_PLAYER_HAND_ROLL_FORWORD,
		STATE_PLAYER_HAND_ROLL_FORWORD_AIR,
		STATE_PLAYER_HAND_ROLL_FORWORD_END,
		STATE_PLAYER_HAND_ROLL_BACK,
		STATE_PLAYER_HAND_ROLL_BACK_AIR,

		STATE_PLAYER_EAT,
		STATE_PLAYER_DAMAGED_LOW,
		STATE_PLAYER_DAMAGED_MEDIUM,
		STATE_PLAYER_DAMAGED_HIGH_BEGIN,
		STATE_PLAYER_DAMAGED_HIGH_END,

		STATE_PLAYER_SKATE_CALL,						//
		STATE_PLAYER_SKATE_STOP_LAND,					//
		STATE_PLAYER_SKATE_STOP_WATER,					//
		STATE_PLAYER_SKATE_RUN,							//
		STATE_PLAYER_SKATE_RUN_SWERVE_L,				//
		STATE_PLAYER_SKATE_RUN_SWERVE_R,				//
		STATE_PLAYER_SKATE_JUMP,						//
		STATE_PLAYER_SKATE_LANDING,						//

		STATE_PLAYER_SWIM_DIE,							//58
		STATE_PLAYER_SWIM_LOOP_A,						//59
		STATE_PLAYER_SWIM_LOOP_B,						//60
		STATE_PLAYER_SWIM_IDLE,							//65
		STATE_PLAYER_SWIM_DASH,							//68

		STATE_PLAYER_GLIDE_UP,							//149
		STATE_PLAYER_GLIDE_UP_END,						//196
		STATE_PLAYER_GLIDE_LOOP,						//150
		STATE_PLAYER_GLIDE_BEGIN_F,						//154
		STATE_PLAYER_GLIDE_LOOP_F,						//151
		STATE_PLAYER_GLIDE_STOP,						//152
		STATE_PLAYER_GLIDE_END,							//153

		STATE_PLAYER_MOUNT_UP,							//189
		STATE_PLAYER_MOUNT_DRIVE,						//190
		STATE_PLAYER_MOUNT_FREE,						//191
		STATE_PLAYER_MOUNT_IDLE,						//192
		STATE_PLAYER_MOUNT_JUMP_START,					//193
		STATE_PLAYER_MOUNT_TURN_L,						//194
		STATE_PLAYER_MOUNT_TURN_R,						//195
		STATE_PLAYER_MOUNT_ROLL,						//192
		STATE_PLAYER_MOUNT_ROLL_AIR,						//192
		STATE_PLAYER_MOUNT_DRIVE_AIR,						//190

		STATE_PLAYER_CLIMB_INTO_DOWN,					 //155
		STATE_PLAYER_CLIMB_INTO_UP,						 //156
		STATE_PLAYER_CLIMB_OUT_ROLL,					 //157
		STATE_PLAYER_CLIMB_OUT,							 //158
		STATE_PLAYER_CLIMB_OUT_JUMP,					 //159
		STATE_PLAYER_CLIMB_STOP,						 //160
		STATE_PLAYER_CLIMB_LEFT,						 //161
		STATE_PLAYER_CLIMB_LEFT_DOWN,					 //162
		STATE_PLAYER_CLIMB_LEFT_UP,						 //163
		STATE_PLAYER_CLIMB_RIGHT,						 //164
		STATE_PLAYER_CLIMB_RIGHT_DOWN,					 //165
		STATE_PLAYER_CLIMB_RIGHT_UP,					 //166
		STATE_PLAYER_CLIMB_UP,							 //167
		STATE_PLAYER_CLIMB_ROLL_LEFT,					 //168
		STATE_PLAYER_CLIMB_ROLL_LEFT_END,				 //169
		STATE_PLAYER_CLIMB_ROLL_RIGHT,					 //170
		STATE_PLAYER_CLIMB_ROLL_RIGHT_END,				 //171
		STATE_PLAYER_CLIMB_ROLL_UP,						 //172
		STATE_PLAYER_CLIMB_ROLL_UP_END,					 //173
		STATE_PLAYER_CLIMB_ROLL_UP_LEFT,				 //174
		STATE_PLAYER_CLIMB_ROLL_UP_LEFT_END,			 //175
		STATE_PLAYER_CLIMB_ROLL_UP_RIGHT,				 //176
		STATE_PLAYER_CLIMB_ROLL_UP_RIGHT_END,			 //177
		STATE_PLAYER_CLIMB_DOWN,						 //178
#pragma endregion Normal

#pragma region Weapon Base
		STATE_PLAYER_ATTACK,
		STATE_PLAYER_ATTACK_AIR,
		STATE_PLAYER_ATTACK_BASE_CHARGE,
		STATE_PLAYER_ATTACK_JUMP_CHARGE,
		STATE_PLAYER_ATTACK_ROLL,

		STATE_PLAYER_SKILL_NORMAL,
		STATE_PLAYER_SKILL_SPECIAL,
		STATE_PLAYER_SKILL_NORMAL_AIR,
		STATE_PLAYER_SKILL_SPECIAL_AIR,
#pragma endregion Weapon Base

#pragma region Sword
		STATE_PLAYER_SWORD_IDLE,

		STATE_PLAYER_SWORD_ATTACK_A,
		STATE_PLAYER_SWORD_ATTACK_B,
		STATE_PLAYER_SWORD_ATTACK_C,
		STATE_PLAYER_SWORD_ATTACK_D,
		STATE_PLAYER_SWORD_ATTACK_E,

		STATE_PLAYER_SWORD_ATTACK_AIR_A,
		STATE_PLAYER_SWORD_ATTACK_AIR_B,
		STATE_PLAYER_SWORD_ATTACK_AIR_C,
		STATE_PLAYER_SWORD_ATTACK_AIR_D,

		STATE_PLAYER_SWORD_ATTACK_BASE_CHARGE,
		STATE_PLAYER_SWORD_ATTACK_JUMP_CHARGE_A,
		STATE_PLAYER_SWORD_ATTACK_JUMP_CHARGE_B,
		STATE_PLAYER_SWORD_ATTACK_JUMP_CHARGE_C,
		STATE_PLAYER_SWORD_ATTACK_ROLL,

		STATE_PLAYER_SWORD_SKILL_NORMAL,
		STATE_PLAYER_SWORD_SKILL_NORMAL_AIR,
		STATE_PLAYER_SWORD_SKILL_SPECIAL,
		STATE_PLAYER_SWORD_SKILL_SPECIAL_A,
		STATE_PLAYER_SWORD_SKILL_SPECIAL_B,
		STATE_PLAYER_SWORD_SKILL_SPECIAL_C,
		STATE_PLAYER_SWORD_SKILL_SPECIAL_D,
		STATE_PLAYER_SWORD_SKILL_SPECIAL_E,

		STATE_PLAYER_SWORD_ROLL_FORWORD,
		STATE_PLAYER_SWORD_ROLL_FORWORD_AIR,
		STATE_PLAYER_SWORD_ROLL_FORWORD_END,
		STATE_PLAYER_SWORD_ROLL_BACK,
		STATE_PLAYER_SWORD_ROLL_BACK_AIR,
#pragma endregion Sword


#pragma region 2Gun
		STATE_PLAYER_2GUN_IDLE,

		STATE_PLAYER_2GUN_ATTACK_A,
		STATE_PLAYER_2GUN_ATTACK_B,
		STATE_PLAYER_2GUN_ATTACK_C,
		STATE_PLAYER_2GUN_ATTACK_D,
		STATE_PLAYER_2GUN_ATTACK_E,

		STATE_PLAYER_2GUN_ATTACK_AIR_A,
		STATE_PLAYER_2GUN_ATTACK_AIR_B,
		STATE_PLAYER_2GUN_ATTACK_AIR_C,

		STATE_PLAYER_2GUN_ATTACK_JUMP_CHARGE_A,
		STATE_PLAYER_2GUN_ATTACK_JUMP_CHARGE_B,
		STATE_PLAYER_2GUN_ATTACK_JUMP_CHARGE_C,

		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_ZOOM_BEGIN,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_ZOOM,

		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_BEGIN,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_WALKFRONT,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_WALKBACK,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_WALKLEFT,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_WALKRIGHT,
		STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE_IDLE,

		/*STATE_PLAYER_2GUN_ATTACK_BASE_CHARGE,
		STATE_PLAYER_2GUN_ATTACK_JUMP_CHARGE,*/
		STATE_PLAYER_2GUN_ATTACK_ROLL,

		STATE_PLAYER_2GUN_SKILL_NORMAL,
		STATE_PLAYER_2GUN_SKILL_NORMAL_AIR,
		STATE_PLAYER_2GUN_SKILL_SPECIAL,
		STATE_PLAYER_2GUN_SKILL_SPECIAL_AIR,

		STATE_PLAYER_2GUN_ROLL_FORWORD,
		STATE_PLAYER_2GUN_ROLL_FORWORD_AIR,
		STATE_PLAYER_2GUN_ROLL_FORWORD_END,
		STATE_PLAYER_2GUN_ROLL_BACK,
		STATE_PLAYER_2GUN_ROLL_BACK_AIR,
#pragma endregion 2Gun

#pragma region ShieldAxe
			STATE_PLAYER_SHIELD_IDLE,
			STATE_PLAYER_AXE_IDLE,

			STATE_PLAYER_SHIELD_ATTACK_A,
			STATE_PLAYER_SHIELD_ATTACK_B,
			STATE_PLAYER_SHIELD_ATTACK_C,
			STATE_PLAYER_SHIELD_ATTACK_D,

			STATE_PLAYER_SHIELD_ATTACK_AIR_A,
			STATE_PLAYER_SHIELD_ATTACK_AIR_B,
			STATE_PLAYER_SHIELD_ATTACK_AIR_C,

			STATE_PLAYER_SHIELD_ATTACK_BASE_CHARGE_BEGIN,
			STATE_PLAYER_SHIELD_ATTACK_BASE_CHARGE_LOOP,
			STATE_PLAYER_SHIELD_ATTACK_BASE_CHARGE_END,

			STATE_PLAYER_SHIELD_ATTACK_JUMP_CHARGE_A,
			STATE_PLAYER_SHIELD_ATTACK_JUMP_CHARGE_B,
			STATE_PLAYER_SHIELD_ATTACK_JUMP_CHARGE_C,

			STATE_PLAYER_SHIELD_ATTACK_ROLL,

			STATE_PLAYER_SHIELD_SKILL_NORMAL_AIR_BEGIN,
			STATE_PLAYER_SHIELD_SKILL_NORMAL_AIR_LOOP,
			STATE_PLAYER_SHIELD_SKILL_NORMAL_AIR_END,

			STATE_PLAYER_SHIELD_ATTACK_SKILL_NORMAL, 
			STATE_PLAYER_SHIELD_ATTACK_SKILL_SPEAICAL,

			STATE_PLAYER_AXE_ATTACK_A,
			STATE_PLAYER_AXE_ATTACK_B,
			STATE_PLAYER_AXE_ATTACK_C,
			STATE_PLAYER_AXE_ATTACK_D,

			STATE_PLAYER_AXE_ATTACK_AIR_A,
			STATE_PLAYER_AXE_ATTACK_AIR_B,
			STATE_PLAYER_AXE_ATTACK_AIR_C,

			STATE_PLAYER_AXE_ATTACK_JUMP_CHARGE_A,
			STATE_PLAYER_AXE_ATTACK_JUMP_CHARGE_B,
			STATE_PLAYER_AXE_ATTACK_JUMP_CHARGE_C,

			STATE_PLAYER_AXE_ATTACK_BASE_CHARGE,

			STATE_PLAYER_AXE_ATTACK_ROLL,

			STATE_PLAYER_AXE_ATTACK_SKILL_NORMAL,

			STATE_PLAYER_AXE_SKILL_NORMAL_AIR_BEGIN,
			STATE_PLAYER_AXE_SKILL_NORMAL_AIR_LOOP,
			STATE_PLAYER_AXE_SKILL_NORMAL_AIR_END,

			STATE_PLAYER_SHIELD_ROLL_FORWORD,
			STATE_PLAYER_SHIELD_ROLL_FORWORD_AIR,
			STATE_PLAYER_SHIELD_ROLL_FORWORD_END,
			STATE_PLAYER_SHIELD_ROLL_BACK,
			STATE_PLAYER_SHIELD_ROLL_BACK_AIR,

			STATE_PLAYER_AXE_ROLL_FORWORD,
			STATE_PLAYER_AXE_ROLL_FORWORD_AIR,
			STATE_PLAYER_AXE_ROLL_FORWORD_END,
			STATE_PLAYER_AXE_ROLL_BACK,
			STATE_PLAYER_AXE_ROLL_BACK_AIR,

#pragma endregion ShieldAxe

#pragma region Cube
			STATE_PLAYER_CUBE_IDLE,

			STATE_PLAYER_CUBE_ATTACK_A,						 //98
			STATE_PLAYER_CUBE_ATTACK_B,						 //99
			STATE_PLAYER_CUBE_ATTACK_C,						 //100
			STATE_PLAYER_CUBE_ATTACK_D,						 //101
			STATE_PLAYER_CUBE_ATTACK_E,						 //102

			STATE_PLAYER_CUBE_ATTACK_AIR_A,					 //107
			STATE_PLAYER_CUBE_ATTACK_AIR_B,					 //108
			STATE_PLAYER_CUBE_ATTACK_AIR_C,					 //109

			STATE_PLAYER_CUBE_ATTACK_BASE_CHARGE,

			STATE_PLAYER_CUBE_ATTACK_JUMP_CHARGE_BEGIN,				 //111
			STATE_PLAYER_CUBE_ATTACK_JUMP_CHARGE_LOOP,				 //112
			STATE_PLAYER_CUBE_ATTACK_JUMP_CHARGE_END,				 //113

			STATE_PLAYER_CUBE_ATTACK_SKILL_NORMAL,			 //103
			STATE_PLAYER_CUBE_ATTACK_SKILL_NORMAL_AIR,		 //104

			STATE_PLAYER_CUBE_ATTACK_SKILL_SPECIAL,			 //114
			STATE_PLAYER_CUBE_ATTACK_SKILL_SPECIAL_AIR,		 //115

			STATE_PLAYER_CUBE_ROLL_FORWORD,
			STATE_PLAYER_CUBE_ROLL_FORWORD_AIR,
			STATE_PLAYER_CUBE_ROLL_FORWORD_END,
			STATE_PLAYER_CUBE_ROLL_BACK,
			STATE_PLAYER_CUBE_ROLL_BACK_AIR,

#pragma endregion Cube


#pragma region UI
			STATE_PLAYER_UI_APPEAR,
			STATE_PLAYER_UI_IDLE,

			STATE_PLAYER_UI_SWORD_APPEAR,
			STATE_PLAYER_UI_SWORD_IDLE,

			STATE_PLAYER_UI_2GUN_APPEAR,
			STATE_PLAYER_UI_2GUN_IDLE,

			STATE_PLAYER_UI_SHIELD_APPEAR,
			STATE_PLAYER_UI_SHIELD_IDLE,

			STATE_PLAYER_UI_CUBE_APPEAR,
			STATE_PLAYER_UI_CUBE_IDLE,

			STATE_PLAYER_UI_NONE_APPEAR,
			STATE_PLAYER_UI_NONE_IDLE,
#pragma endregion UI

#pragma region MOTORCYCLE
		STATE_MOTORCYCLE_IDLE,
		STATE_MOTORCYCLE_JUMP_START,
		STATE_MOTORCYCLE_JUMP_LOOP,
		STATE_MOTORCYCLE_JUMP_RUN,
		STATE_MOTORCYCLE_JUMP_END,
		STATE_MOTORCYCLE_RUN,

#pragma endregion MOTORCYCLE

		// Boss
		STATE_BOSS_SITDOWN,
		STATE_BOSS_AWAKE,
		STATE_BOSS_IDLE,
		STATE_BOSS_WALK,

		STATE_BOSS_ATTACK,
		STATE_BOSS_SWINGATTACK,
		STATE_BOSS_JUMPATTACK,
		STATE_BOSS_KEEPATTACK,
		STATE_BOSS_DASH,
		STATE_BOSS_ULTRAATTACK,
		STATE_BOSS_SHIELD,

		// Boss_Angel
		STATE_BOSS_ANGEL_READY,				//22
		STATE_BOSS_ANGEL_STAND,				//10
		STATE_BOSS_ANGEL_IDLE,				//13
		STATE_BOSS_ANGEL_BACK,				//16
		STATE_BOSS_ANGEL_TURNL,				//14
		STATE_BOSS_ANGEL_TURNR,				//15
		STATE_BOSS_ANGEL_RUN,				//17
		STATE_BOSS_ANGEL_RUNL,				//18
		STATE_BOSS_ANGEL_RUNR,				//19

		STATE_BOSS_ANGEL_SWING_ATTACK,		//5

		STATE_BOSS_ANGEL_LASER_ATTACK,		//7
		STATE_BOSS_ANGEL_LASER_ATTACKA,		//0 -> 1, 2
		STATE_BOSS_ANGEL_LASER_ATTACKB,		//1
		STATE_BOSS_ANGEL_LASER_ATTACKC,		//2

		STATE_BOSS_ANGEL_SKILL_ATTACKA,		//3
		STATE_BOSS_ANGEL_SKILL_ATTACKB,		//4

		STATE_BOSS_ANGEL_ULT_ATTACK,		//8
		STATE_BOSS_ANGEL_ULT_ATTACK_END,	//9

		STATE_BOSS_ANGEL_SHIELD,			//12
		STATE_BOSS_ANGEL_RESET,				//11

		STATE_BOSS_ANGEL_DEAD,				//21

		// Boss_Dragon
		STATE_BOSS_DRAGON_IDLE,				//9
		STATE_BOSS_DRAGON_CAM_ACTION,				//9

		//Reset
		STATE_BOSS_DRAGON_APEAR,			//8
		STATE_BOSS_DRAGON_DOEND,			//0
		STATE_BOSS_DRAGON_RUNEND,			//8

		STATE_BOSS_DRAGON_CHASE,			//8
		STATE_BOSS_DRAGON_RUN,				//9
		STATE_BOSS_DRAGON_PATROL,			//9
		STATE_BOSS_DRAGON_PATROL_APEAR,		//22

		STATE_BOSS_DRAGON_TURNL,			//10
		STATE_BOSS_DRAGON_TURNR,			//11

		STATE_BOSS_DRAGON_ATTACK_01,		//0
		STATE_BOSS_DRAGON_ATTACK_02,		//1
		STATE_BOSS_DRAGON_ATTACK_03,		//2
		STATE_BOSS_DRAGON_ATTACK_04,		//3
		STATE_BOSS_DRAGON_ATTACK_05,		//4
		STATE_BOSS_DRAGON_ATTACK_08,		//7
		STATE_BOSS_DRAGON_ATTACK_09,		//26
		//STATE_BOSS_DRAGON_ATTACK_06,		//5
		//STATE_BOSS_DRAGON_ATTACK_07,		//6
		//STATE_BOSS_DRAGON_ATTACK_08,		//7

		STATE_BOSS_DRAGON_ULT_ATTACK_1,		//26
		STATE_BOSS_DRAGON_ULT_ATTACK_2,		//27
		STATE_BOSS_DRAGON_ULT_ATTACK_3,		//28

		STATE_BOSS_DRAGON_FALL_LOOP,		//21
		STATE_BOSS_DRAGON_FALL_LAND,		//20

		STATE_BOSS_DRAGON_WEAK_BEGIN,		//29
		STATE_BOSS_DRAGON_WEAK_END,			//30
		STATE_BOSS_DRAGON_WEAK_LOOP,		//31

		STATE_BOSS_DRAGON_DEAD,				//18

		//STATE_BULLET
		STATE_BULLET_DRAGON_PATROL,			//22
		STAET_DRAGON_END,


		// Boss_Robella
		// Boss_Robella 정찰상태
		STATE_BOSS_ROBELLA_READY,			// 33
		STATE_BOSS_ROBELLA_CHANGE_PHASE,	// 15
		STATE_BOSS_ROBELLA_APEAR,			// 0
		STATE_BOSS_ROBELLA_CAM_ACTION,

		// 1페이즈 IDLE
		STATE_BOSS_ROBELLA_IDLE,			// 33
		// 2페이즈 IDLE
		STATE_BOSS_ROBELLA_IDLE2,			// 18

		// 1페이즈 공격
		STATE_BOSS_ROBELLA_ATTACK_01,		// 1 불똥
		STATE_BOSS_ROBELLA_ATTACK_02_BEGIN,	// 2 
		STATE_BOSS_ROBELLA_ATTACK_02_LOOP,	// 4 꿀렁꿀렁
		STATE_BOSS_ROBELLA_ATTACK_02_END,	// 3
		STATE_BOSS_ROBELLA_ATTACK_03,		// 5 빙글빙글

		//  2페이즈 공격	
		STATE_BOSS_ROBELLA_ATTACK_04,		// 6 회전후 등장
		STATE_BOSS_ROBELLA_ATTACK_05,		// 8 채찎
		STATE_BOSS_ROBELLA_ATTACK_06,		// 10 애니메이션 두배속도해야함 채찍2
		STATE_BOSS_ROBELLA_ATTACK_07,		// 11 삿대질
		STATE_BOSS_ROBELLA_ATTACK_08,		// 12 혼자화이팅
		STATE_BOSS_ROBELLA_ATTACK_09_BEGIN,	// 13 어퍼컷함
		STATE_BOSS_ROBELLA_ATTACK_09_END,	// 14 어퍼컷 마무리

		STATE_BOSS_ROBELLA_ATTACK_ULT_READY,// 17 혼자 화이팅2
		STATE_BOSS_ROBELLA_ATTACK_ULT,		// 19 꽃잎으로 숨고 꿀럭꿀럭하다가 등장해서 회전

		STATE_BOSS_ROBELLA_DEAD,			// 29
		STATE_BOSS_ROBELLA_DEAD_LOOP,		// 30

		STATE_BOSS_ROBELLA_1PHASE_DOWN,		// 40
		STATE_BOSS_ROBELLA_1PHASE_DOWN_LOOP,// 41
		STATE_BOSS_ROBELLA_1PHASE_DOWN_UP,	// 42

		STATE_BOSS_ROBELLA_2PHASE_DOWN,		// 36
		STATE_BOSS_ROBELLA_2PHASE_DOWN_LOOP,// 38
		STATE_BOSS_ROBELLA_2PHASE_DOWN_UP,	// 37
		
		STATE_BOSS_ROBELLA_END,
			
		//Boss_Weaver
		STATE_BOSS_WEAVER_IDLE,				//21
		STATE_BOSS_WEAVER_CAM_ACTION,

		STATE_BOSS_WEAVER_APEAR,			//22 대기->아이들
		STATE_BOSS_WEAVER_RESET,			//15 모든 동작끝
		STATE_BOSS_WEAVER_READY,			//36 대기

		STATE_BOSS_WEAVER_WALK_B,			//25 후진
		STATE_BOSS_WEAVER_WALK_F,			//26 전진
		STATE_BOSS_WEAVER_WALK_L,			//27 좌
		STATE_BOSS_WEAVER_WALK_R,			//28 우

		STATE_BOSS_WEAVER_TURN_L,			//23 왼쪽으로 돎
		STATE_BOSS_WEAVER_TURN_R,			//24 오른쪽으로 돎

		STATE_BOSS_WEAVER_ATTACK_01,		//0	기본 평타 두대
		STATE_BOSS_WEAVER_ATTACK_02,		//1 칼 난자
		STATE_BOSS_WEAVER_ATTACK_03,		//2 칼을 한자루씩 날리고 바닥으로 숨겨서 다시 가져옴
		STATE_BOSS_WEAVER_ATTACK_04,		//3 뭔가 전체공격느낌의 칼을 사방으로 날리고 다시모아옴
		STATE_BOSS_WEAVER_ATTACK_05_1,		//4 대쉬공격 시작
		STATE_BOSS_WEAVER_ATTACK_05_2,		//5 대쉬공격 끝
		STATE_BOSS_WEAVER_ATTACK_06_BEGIN,	//6 4번보다 작은 느낌의 전체공격기
		STATE_BOSS_WEAVER_ATTACK_06_BREAK,	//7 중간에 조건 달성시 그로기 -> WEAKLOOP로 이어짐
		STATE_BOSS_WEAVER_ATTACK_06_END,	//8 종료
		STATE_BOSS_WEAVER_ATTACK_06_LOOP,	//9 루프
		STATE_BOSS_WEAVER_ATTACK_07,		//10 레이저 포
		STATE_BOSS_WEAVER_ATTACK_08,		//11 한자루씩 날리고 땅속으로 숨겨서 되돌아옴
		STATE_BOSS_WEAVER_ATTACK_09,		//13 칼을 모아서 바닥에 꽂음 충격파 좋을듯
		STATE_BOSS_WEAVER_ATTACK_10,		//14 칼을 모아서 재정비하는 느낌 리셋2 로 쓰면될듯
		STATE_BOSS_WEAVER_ATTACK_11_BEGIN,	//16 타깃에 칼을 꽂아서 들어올림
		STATE_BOSS_WEAVER_ATTACK_11_LOOP,	//19 딜박히는중
		STATE_BOSS_WEAVER_ATTACK_11_END,	//18 끝
		STATE_BOSS_WEAVER_ATTACK_12,		//17 타깃에 그냥 칼을 꽂아서 공격

		STATE_BOSS_WEAVER_SHIELD,			//20 실드 생기게하면댐

		STATE_BOSS_WEAVER_WEAK_BEGIN,		//37 그로기 시작 특정조건
		STATE_BOSS_WEAVER_WEAK_END,			//39 그로기 끝
		STATE_BOSS_WEAVER_WEAK_LOOP,		//38 그로기 중

		STATE_BOSS_WEAVER_DEAD,				//34 주금
		STATE_BOSS_WEAVER_END,

		//Leviathan
		STATE_BOSS_LEVIATHAN_APEAR,

		STATE_BOSS_LEVIATHAN_IDLE,
		STATE_BOSS_LEVIATHAN_WALK,
		STATE_BOSS_LEVIATHAN_WEAK,
		STATE_BOSS_LEVIATHAN_JUMP_TURNL,
		STATE_BOSS_LEVIATHAN_JUMP_TURNR,

		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_FR,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_BL_A,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_BL_B,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_BL_C,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_F_A,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_F_B,
		STATE_BOSS_LEVIATHAN_ATTACK_DOWN_F_C,
		STATE_BOSS_LEVIATHAN_ATTACK_UP_FL,
		STATE_BOSS_LEVIATHAN_ATTACK_UP_BR,
		STATE_BOSS_LEVIATHAN_ATTACK_UP_F,

		STATE_BOSS_LEVIATHAN_ROAR_0,

		STATE_BOSS_LEVIATHAN_LOOK_CENTER_ROAR,
		STATE_BOSS_LEVIATHAN_LOOK_OUT_ROAR,
		STATE_BOSS_LEVIATHAN_TURN,
		STATE_BOSS_LEVIATHAN_JUMP_TURN,

		STATE_BOSS_LEVIATHAN_DEAD,

		//STATE_BOSS_LEVIATHAN_TURN_ROAR_1,

		STATE_BOSS_LEVIATHAN_END,





		//Leviathan_90

		STATE_BOSS_LEVIATHAN_LARGE_MOVE_A,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_B,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_C,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_D,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_E,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_F,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_G,
		STATE_BOSS_LEVIATHAN_LARGE_MOVE_H,

		STATE_BOSS_LEVIATHAN_LARGE_END,


#pragma region Enemy_HyenaGang_Minions

		STATE_ENEMY_HYENAGANG_MINIONS_DANCE,

		STATE_ENEMY_HYENAGANG_MINIONS_IDLE_NORMAL,
		STATE_ENEMY_HYENAGANG_MINIONS_IDLE_BATTLE,
		STATE_ENEMY_HYENAGANG_MINIONS_WALK,
		STATE_ENEMY_HYENAGANG_MINIONS_FIND,

		STATE_ENEMY_HYENAGANG_MINIONS_RUN,
		STATE_ENEMY_HYENAGANG_MINIONS_RUN_RETURN,

		STATE_ENEMY_HYENAGANG_MINIONS_ATTACK_NORMAL_SHOT,
		STATE_ENEMY_HYENAGANG_MINIONS_ATTACK_CHARGE_SHOT,

		STATE_ENEMY_HYENAGANG_MINIONS_TURN_L,
		STATE_ENEMY_HYENAGANG_MINIONS_TURN_R,

		STATE_ENEMY_HYENAGANG_MINIONS_WALK_B,
		STATE_ENEMY_HYENAGANG_MINIONS_WALK_F,
		STATE_ENEMY_HYENAGANG_MINIONS_WALK_L,
		STATE_ENEMY_HYENAGANG_MINIONS_WALK_R,

		STATE_ENEMY_HYENAGANG_MINIONS_DAMAGE_F,
		STATE_ENEMY_HYENAGANG_MINIONS_DAMAGE_B,
		STATE_ENEMY_HYENAGANG_MINIONS_DAMAGE_L,
		STATE_ENEMY_HYENAGANG_MINIONS_DAMAGE_R,

		STATE_ENEMY_HYENAGANG_MINIONS_DEAD_1,
		STATE_ENEMY_HYENAGANG_MINIONS_DEAD_END,
#pragma endregion Enemy_HyenaGang_Minions

#pragma region Enemy_HyenaGang_Shooter

		STATE_ENEMY_HYENAGANG_SHOOTER_DANCE,

		STATE_ENEMY_HYENAGANG_SHOOTER_IDLE_NORMAL,
		STATE_ENEMY_HYENAGANG_SHOOTER_IDLE_BATTLE,
		STATE_ENEMY_HYENAGANG_SHOOTER_WALK,
		STATE_ENEMY_HYENAGANG_SHOOTER_FIND,

		STATE_ENEMY_HYENAGANG_SHOOTER_RUN,
		STATE_ENEMY_HYENAGANG_SHOOTER_RUN_RETURN,

		STATE_ENEMY_HYENAGANG_SHOOTER_ATTACK_NORMAL_SHOT,
		STATE_ENEMY_HYENAGANG_SHOOTER_ATTACK_CHARGE_SHOT,

		STATE_ENEMY_HYENAGANG_SHOOTER_TURN_L,
		STATE_ENEMY_HYENAGANG_SHOOTER_TURN_R,

		STATE_ENEMY_HYENAGANG_SHOOTER_WALK_B,
		STATE_ENEMY_HYENAGANG_SHOOTER_WALK_F,
		STATE_ENEMY_HYENAGANG_SHOOTER_WALK_L,
		STATE_ENEMY_HYENAGANG_SHOOTER_WALK_R,

		STATE_ENEMY_HYENAGANG_SHOOTER_DAMAGE_F,
		STATE_ENEMY_HYENAGANG_SHOOTER_DAMAGE_B,
		STATE_ENEMY_HYENAGANG_SHOOTER_DAMAGE_L,
		STATE_ENEMY_HYENAGANG_SHOOTER_DAMAGE_R,

		STATE_ENEMY_HYENAGANG_SHOOTER_DEAD_1,
		STATE_ENEMY_HYENAGANG_SHOOTER_DEAD_END,
#pragma endregion Enemy_HyenaGang_Shooter

#pragma region Enemy_Gangster_Cap
		STATE_ENEMY_GANGSTER_CAP_DANCE,
		STATE_ENEMY_GANGSTER_CAP_SLEEP_END,
		STATE_ENEMY_GANGSTER_CAP_SLEEP_1,
		STATE_ENEMY_GANGSTER_CAP_STANDUP,

		STATE_ENEMY_GANGSTER_CAP_IDLE_NORMAL,
		STATE_ENEMY_GANGSTER_CAP_IDLE_BATTLE,
		STATE_ENEMY_GANGSTER_CAP_WALK,
		STATE_ENEMY_GANGSTER_CAP_FIND,

		STATE_ENEMY_GANGSTER_CAP_RUN,
		STATE_ENEMY_GANGSTER_CAP_RUN_RETURN,

		STATE_ENEMY_GANGSTER_CAP_ATTACK_SWING,
		STATE_ENEMY_GANGSTER_CAP_ATTACK_DASH,
		STATE_ENEMY_GANGSTER_CAP_ATTACK_TURNTURN,

		STATE_ENEMY_GANGSTER_CAP_TURN_L,
		STATE_ENEMY_GANGSTER_CAP_TURN_R,

		STATE_ENEMY_GANGSTER_CAP_WALK_B,
		STATE_ENEMY_GANGSTER_CAP_WALK_F,
		STATE_ENEMY_GANGSTER_CAP_WALK_L,
		STATE_ENEMY_GANGSTER_CAP_WALK_R,

		STATE_ENEMY_GANGSTER_CAP_DAMAGE_B,
		STATE_ENEMY_GANGSTER_CAP_DAMAGE_L,
		STATE_ENEMY_GANGSTER_CAP_DAMAGE_R,

		STATE_ENEMY_GANGSTER_CAP_DEAD_1,
		STATE_ENEMY_GANGSTER_CAP_DEAD_END,
#pragma endregion Enemy_Gangster_Cap

#pragma region Enemy_Mutition
		STATE_ENEMY_MUTATION_DANCE,

		STATE_ENEMY_MUTATION_IDLE_NORMAL,
		STATE_ENEMY_MUTATION_IDLE_BATTLE,
		STATE_ENEMY_MUTATION_WALK,
		STATE_ENEMY_MUTATION_FIND,

		STATE_ENEMY_MUTATION_RUN,
		STATE_ENEMY_MUTATION_RUN_RETURN,

		STATE_ENEMY_MUTATION_ATTACK_UPHIT,
		STATE_ENEMY_MUTATION_ATTACK_DOWNHIT,

		STATE_ENEMY_MUTATION_TURN_L,
		STATE_ENEMY_MUTATION_TURN_R,

		STATE_ENEMY_MUTATION_WALK_B,
		STATE_ENEMY_MUTATION_WALK_F,
		STATE_ENEMY_MUTATION_WALK_L,
		STATE_ENEMY_MUTATION_WALK_R,

		STATE_ENEMY_MUTATION_DAMAGE_F,
		STATE_ENEMY_MUTATION_DAMAGE_B,
		STATE_ENEMY_MUTATION_DAMAGE_L,
		STATE_ENEMY_MUTATION_DAMAGE_R,

		STATE_ENEMY_MUTATION_DEAD_1,
		STATE_ENEMY_MUTATION_DEAD_END,

		STATE_ENEMY_MUTATION_EAT,
		STATE_ENEMY_MUTATION_EAT_FIND,


#pragma endregion Enemy_Mutition

#pragma region Enemy_Mutition_Mechanic

			STATE_ENEMY_MUTATION_MECHANIC_DANCE,
								
			STATE_ENEMY_MUTATION_MECHANIC_IDLE_NORMAL,
			STATE_ENEMY_MUTATION_MECHANIC_IDLE_BATTLE,
			STATE_ENEMY_MUTATION_MECHANIC_WALK,
			STATE_ENEMY_MUTATION_MECHANIC_FIND,
								
			STATE_ENEMY_MUTATION_MECHANIC_RUN,
			STATE_ENEMY_MUTATION_MECHANIC_RUN_RETURN,
								
			STATE_ENEMY_MUTATION_MECHANIC_ATTACK_UPHIT,
			STATE_ENEMY_MUTATION_MECHANIC_ATTACK_DOWNHIT,
								
			STATE_ENEMY_MUTATION_MECHANIC_TURN_L,
			STATE_ENEMY_MUTATION_MECHANIC_TURN_R,
								
			STATE_ENEMY_MUTATION_MECHANIC_WALK_B,
			STATE_ENEMY_MUTATION_MECHANIC_WALK_F,
			STATE_ENEMY_MUTATION_MECHANIC_WALK_L,
			STATE_ENEMY_MUTATION_MECHANIC_WALK_R,
								
			STATE_ENEMY_MUTATION_MECHANIC_DAMAGE_F,
			STATE_ENEMY_MUTATION_MECHANIC_DAMAGE_B,
			STATE_ENEMY_MUTATION_MECHANIC_DAMAGE_L,
			STATE_ENEMY_MUTATION_MECHANIC_DAMAGE_R,
								
			STATE_ENEMY_MUTATION_MECHANIC_DEAD_1,
			STATE_ENEMY_MUTATION_MECHANIC_DEAD_END,
#pragma endregion Enemy_Mutition_Mechanic

#pragma region Enemy_Habaka_Admiral

		STATE_ENEMY_HABAKA_ADMIRAL_DANCE,

		STATE_ENEMY_HABAKA_ADMIRAL_IDLE_NORMAL,
		STATE_ENEMY_HABAKA_ADMIRAL_IDLE_BATTLE,
		STATE_ENEMY_HABAKA_ADMIRAL_WALK,
		STATE_ENEMY_HABAKA_ADMIRAL_FIND,

		STATE_ENEMY_HABAKA_ADMIRAL_RUN,
		STATE_ENEMY_HABAKA_ADMIRAL_RUN_RETURN,

		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_FRONTJUMP,
		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_PUNCH_A,
		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_PUNCH_B,
		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_KICK_A,
		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_KICK_B,
		STATE_ENEMY_HABAKA_ADMIRAL_ATTACK_SKILL_A,
		STATE_ENEMY_HABAKA_ADMIRAL_TURN_L,
		STATE_ENEMY_HABAKA_ADMIRAL_TURN_R,

		STATE_ENEMY_HABAKA_ADMIRAL_WALK_B,
		STATE_ENEMY_HABAKA_ADMIRAL_WALK_F,
		STATE_ENEMY_HABAKA_ADMIRAL_WALK_L,
		STATE_ENEMY_HABAKA_ADMIRAL_WALK_R,

		STATE_ENEMY_HABAKA_ADMIRAL_DAMAGE_F,
		STATE_ENEMY_HABAKA_ADMIRAL_DAMAGE_B,
		STATE_ENEMY_HABAKA_ADMIRAL_DAMAGE_L,
		STATE_ENEMY_HABAKA_ADMIRAL_DAMAGE_R,

			STATE_ENEMY_HABAKA_ADMIRAL_DEAD_1,
			STATE_ENEMY_HABAKA_ADMIRAL_DEAD_END,
#pragma endregion Enemy_Habaka_Admiral

#pragma region Enemy_MechanicalCity_Gunner

		STATE_ENEMY_MECHANICALCITY_GUNNER_IDLE_NORMAL,
		STATE_ENEMY_MECHANICALCITY_GUNNER_IDLE_BATTLE,
		STATE_ENEMY_MECHANICALCITY_GUNNER_WALK,
		STATE_ENEMY_MECHANICALCITY_GUNNER_FIND,

		STATE_ENEMY_MECHANICALCITY_GUNNER_RUN,
		STATE_ENEMY_MECHANICALCITY_GUNNER_RUN_RETURN,

		STATE_ENEMY_MECHANICALCITY_GUNNER_ATTACK_THROWBOMB,
		STATE_ENEMY_MECHANICALCITY_GUNNER_ATTACK_SERIESSHOT_BEGIN,
		STATE_ENEMY_MECHANICALCITY_GUNNER_ATTACK_SERIESSHOT_ING,
		STATE_ENEMY_MECHANICALCITY_GUNNER_ATTACK_SERIESSHOT_END,

				STATE_ENEMY_MECHANICALCITY_GUNNER_TURN_L,
				STATE_ENEMY_MECHANICALCITY_GUNNER_TURN_R,
							
				STATE_ENEMY_MECHANICALCITY_GUNNER_WALK_B,
				STATE_ENEMY_MECHANICALCITY_GUNNER_WALK_F,
				STATE_ENEMY_MECHANICALCITY_GUNNER_WALK_L,
				STATE_ENEMY_MECHANICALCITY_GUNNER_WALK_R,
							
				STATE_ENEMY_MECHANICALCITY_GUNNER_DAMAGE_F,
				STATE_ENEMY_MECHANICALCITY_GUNNER_DAMAGE_B,
				STATE_ENEMY_MECHANICALCITY_GUNNER_DAMAGE_L,
				STATE_ENEMY_MECHANICALCITY_GUNNER_DAMAGE_R,
							
				STATE_ENEMY_MECHANICALCITY_GUNNER_DEAD_1,
				STATE_ENEMY_MECHANICALCITY_GUNNER_DEAD_END,
#pragma endregion Enemy_MechanicalCity_Gunner

#pragma region Enemy_MechanicalCity_SwordGhost

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_IDLE_NORMAL,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_IDLE_BATTLE,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_WALK,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_FIND,

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_RUN,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_RUN_RETURN,

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_ATTACK_STAND,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_ATTACK_MOVING,

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_TURN_L,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_TURN_R,

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_WALK_B,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_WALK_F,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_WALK_L,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_WALK_R,

		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_DAMAGE_B,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_DAMAGE_L,
		STATE_ENEMY_MECHANICALCITY_SWORDGHOST_DAMAGE_R,

				STATE_ENEMY_MECHANICALCITY_SWORDGHOST_DEAD_END,
#pragma endregion Enemy_MechanicalCity_SwordGhost

#pragma region Enemy_MechanicalCity_DoubleEdgedSwordAdept

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_IDLE_NORMAL,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_IDLE_BATTLE,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_WALK,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_FIND,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_RUN,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_RUN_RETURN,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_ATTACK_SWING,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_ATTACK_DASH,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_ATTACK_SPECIAL_BEGIN,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_ATTACK_SPECIAL_ING,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_ATTACK_SPECIAL_END,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_TURN_L,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_TURN_R,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_WALK_B,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_WALK_F,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_WALK_L,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_WALK_R,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_DAMAGE_B,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_DAMAGE_L,
				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_DAMAGE_R,

				STATE_ENEMY_MECHANICALCITY_DOUBLEEDGEDSWORDADEPT_DEAD_END,
#pragma endregion Enemy_MechanicalCity_DoubleEdgedSwordAdept

#pragma region Enemy_MechanicalCity_DoorKeeper

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_IDLE_NORMAL,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_IDLE_BATTLE,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_WALK,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_FIND,

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_RUN,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_RUN_RETURN,

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_ATTACK_CHOP,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_ATTACK_JUMPCHOP,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_ATTACK_kEEPHITTING,


				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_TURN_L,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_TURN_R,

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_WALK_B,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_WALK_F,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_WALK_L,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_WALK_R,

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_DAMAGE_B,
				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_DAMAGE_B2,

				STATE_ENEMY_MECHANICALCITY_DOORKEEPER_DEAD_END,

#pragma endregion Enemy_MechanicalCity_DoubleEdgedSwordAdept

		///////////////////////////////////////////////////////////only_idle

		//Enemy_Mutition_HunterDog
		STATE_ENEMY_MUTATION_HUNTERDOG_IDLE_NORMAL,		
		//Enemy_Mutation_Orc
		STATE_ENEMY_MUTATION_ORC_IDLE_NORMAL,

#pragma region Enemy_HunterDog
					STATE_ENEMY_HUNTERDOG_IDLE_NORMAL,
					STATE_ENEMY_HUNTERDOG_IDLE_BATTLE,
					STATE_ENEMY_HUNTERDOG_IDLE_ACT_A,

					STATE_ENEMY_HUNTERDOG_RUN,
					STATE_ENEMY_HUNTERDOG_RUN_RETURN,

					STATE_ENEMY_HUNTERDOG_WALK,

					STATE_ENEMY_HUNTERDOG_WALK_B,
					STATE_ENEMY_HUNTERDOG_WALK_L,
					STATE_ENEMY_HUNTERDOG_WALK_R,

					STATE_ENEMY_HUNTERDOG_WALK_TURN_L,
					STATE_ENEMY_HUNTERDOG_WALK_TURN_R,

					STATE_ENEMY_HUNTERDOG_ATTACK_BITE,
					STATE_ENEMY_HUNTERDOG_ATTACK_FIND_DASH_BITE,

					STATE_ENEMY_HUNTERDOG_DAMAGE_B,
					STATE_ENEMY_HUNTERDOG_DAMAGE_B_BACK,
					STATE_ENEMY_HUNTERDOG_DAMAGE_L,
					STATE_ENEMY_HUNTERDOG_DAMAGE_R,

					STATE_ENEMY_HUNTERDOG_DEAD_1,
					STATE_ENEMY_HUNTERDOG_DEAD_2,
					STATE_ENEMY_HUNTERDOG_DEAD_END,
#pragma endregion Enemy_HunterDog



#pragma region Npc
		// Shirley
		STATE_NCP_SHIRLEY_IDLE,
		STATE_NCP_SHIRLEY_BRILLIANT,
		STATE_NCP_SHIRLEY_GREETING,
		STATE_NCP_SHIRLEY_HUNGRY,
		STATE_NCP_SHIRLEY_SURPRISE,
		STATE_NCP_SHIRLEY_THANK,
		STATE_NCP_SHIRLEY_CONVERSATION_A,
		STATE_NCP_SHIRLEY_CONVERSATION_B,
		STATE_NCP_SHIRLEY_CONVERSATION_C,
		STATE_NCP_SHIRLEY_WORRY_A,
		STATE_NCP_SHIRLEY_WORRY_B,

		// Cooker
		STATE_NCP_COOKER_IDLE,
		STATE_NCP_COOKER_COOKING,
		STATE_NCP_COOKER_COOKING_COMPLETE,
#pragma endregion Npc

		STATE_END,
	};


	enum ENEMY_NORMAL
	{

		HYENAGANG_MINIONS = 10,
		HYENAGANG_SHOOTER,
		GANGSTER_CAP,

		MUTATION,
		MUTATION_MECHANIC,
		HABAKA_ADMIRAL,

		MUTATION_ORC,
		HUNTERDOG,
		MUTATION_HUNTERDOG,



		MECHANICALCITY_DOUBLEEDGEDSWORDADEPT,
		MECHANICALCITY_SWORDGHOST,
		MECHANICALCITY_GUNNER,
		MECHANICALCITY_DOORKEEPER,

		LEVIATHAN_CRYSTAL,

		ENEMY_NORMAL_END
	};

	enum ENEMY_BOSS
	{
		ENEMY_BOSS_ANGEL = 10,
		ENEMY_BOSS_FROSTDRAGON,
		ENEMY_BOSS_WEAVER,
		ENEMY_BOSS_ROBELLA,
		ENEMY_BOSS_LEVIATHAN,

		ENEMY_BOSS_END
	};

	enum ENEMY_BULLET
	{
		ENEMY_BULLET_DEFAULT = 10,
		ENEMY_BULLET_FROSTDRAGON,
		ENEMY_BULLET_THUNDER,

		ENEMY_BULLET_ARROW,

		ENEMY_WEAVER_FROZEN,
		ENEMY_WEAVER_HURRICANE,
		ENEMY_WEAVER_SHOCKWAVE,

		ENEMY_ROBELLA_FIREBALL,
		ENEMY_ROBELLA_FIREBALL2,
		ENEMY_ROBELLA_FIRESTROM,
		ENEMY_ROBELLA_FIRESTROM2,
		ENEMY_ROBELLA_POISONFOG,

		ENEMY_LEVIATHAN_FIREBALL,
		ENEMY_LEVIATHAN_THUNDER,
		ENEMY_LEVIATHAN_ICESPEAR,

		ENEMY_BULLET_END
	};

	//Animation Type
	enum WEAPON_TYPE
	{
		WEAPON_DEFAULT,

		WEAPON_SWORD,
		WEAPON_SPEAR,
		WEAPON_GUN,
		WEAPON_2GUN,
		WEAPON_2GUN_BULLET,
		WEAPON_2GUN_BULLET_ZOOM,
		WEAPON_2GUN_BULLET_NORMAL,
		WEAPON_2GUN_BULLET_SPECIAL,
		WEAPON_2GUN_BULLET_SPECIAL_SUB,
		WEAPON_HAMMER,
		WEAPON_IMMORTAL,
		WEAPON_MARK,
		WEAPON_SICKLE,
		WEAPON_AXE,
		WEAPON_SHIELD,
		WEAPON_SHIELDAXE,
		WEAPON_CUBE,
		WEAPON_CUBE_BULLET,
		WEAPON_TIME_ILLUSION,

		WEAPON_NONE,

		WEAPON_HAND1,
		WEAPON_HAND2,
		WEAPON_HAND3,
		WEAPON_HAND4,
		WEAPON_HAND5,
		WEAPON_HAND6,
		WEAPON_HAND7,
		WEAPON_HAND8,
		WEAPON_HAND9,

		WEAPON_TOOL,

		/*Mobility*/
		MOBILITY_GLIDER,
		MOBILITY_MOTORCYCLE,

		/*Weapon_Enemy*/
		WEAPON_ENEMY_STIC,
		WEAPON_ENEMY_BOW,
		WEAPON_ENEMY_WASTEBASKET,
		WEAPON_ENEMY_HAMMER,

		WEAPON_END,
	};

	enum WEAPON_SLOT
	{
		WPN_SLOT_M,
		WPN_SLOT_L,
		WPN_SLOT_R,

		WPN_SLOT_END,
	};

	enum ELEMENTAL_PROPERTIE
	{
		ELEMENTAL_DEFAULT = 10,

		ELEMENTAL_FIRE,
		ELEMENTAL_ICE,
		ELEMENTAL_LIGHTNING,
		ELEMENTAL_MELEE,

		ELEMENTAL_END,
	};

	enum ITEM_TYPE
	{
		ITEM_DEFAULT,
		ITEM_GOLDCORE,
		ITEM_BLACKCORE,

		ITEM_MUSHROOM,  // 버섯
		ITEM_CACTUS,    // 선인장 볼
		ITEM_BEET,	    // 비트	
		ITEM_BRACKEN,   // 고사리
		ITEM_WHEAT,	    // 호미키밀
		ITEM_LETTUCE,   // 상추
		ITEM_SHELL,     // 호리조개	
		ITEM_HERMITCRAB,// 소라게

		ITEM_BRACKEN_SOUP,		// 고사리탕
		ITEM_CACTUS_JUICE,		// 선인장주스
		ITEM_MUSHROOM_TOASTING, // 버섯볶음
		ITEM_HERMITCRAB_SOUP,	// 소라게탕
		ITEM_WHEAT_BREAD,		// 잡곡빵
		ITEM_LETTUCE_SALAD,		// 상추샐러드
		ITEM_SHELL_STEW,		// 조개전골
		ITEM_BEET_SOUP,			// 비트수프

		ITEM_END,
	};

	enum ORDER_TYPE
	{
		ORDER_BLACKCORE = 2,

		ORDER_MUSHROOM,  // 버섯3
		ORDER_CACTUS,    // 선인장 볼4
		ORDER_BEET,	     // 비트	5
		ORDER_BRACKEN,   // 고사리6
		ORDER_WHEAT,	 // 호미키밀7
		ORDER_LETTUCE,   // 상추8
		ORDER_SHELL,     // 호리조개	9
		ORDER_HERMITCRAB,// 소라게10
	
		ORDER_2GUN,		//11
		ORDER_SHIELDAXE,//12
		ORDER_CUBE,		//13
	
		ORDER_END,
	};

	enum QUEST_TYPE
	{
		// 초반 뽑기 퀘스트
		QUEST_CUBE_ORDER,

		// 로벨라 퀘스트
		QUEST_COLLECT_LETTUCE,
		QUEST_KILL_GANG_SWARM,
		QUEST_KILL_GANG_CAP,
		QUEST_KILL_ROBELLA,
		QUEST_MAKE_COOKING,

		// 주문
		QUEST_ORDER,

		// 프로스트 드래곤 퀘스트
		QUEST_KILL_MECHANICALCITY_SWARM,
		QUEST_KILL_DOORKEEPER,
		QUEST_KILL_JUMPING_FROSTDRAGON,
		QUEST_MAKE_COOKING_1,

		// 웨버 퀘스트
		QUEST_KILL_MUTATION,
		QUEST_KILL_HABAKA,
		QUEST_KILL_WEAVER,
		QUEST_MAKE_COOKING_2,

		QUEST_END,
	};

	enum PORTAL_TYPE
	{
		PORTAL_DRAGON,
		PORTAL_WEAVER,
		PORTAL_VILLAGE,
		PORTAL_LEVIATHAN,

		PORTAL_END
	};

	enum REGION_TYPE
	{
		REGION_VILLAGE,
		REGION_ROBELLA,
		REGION_DRAGON,
		REGION_WEAVER,

		REGION_END
	};

	enum MINIGAME_TYPE
	{
		MINIGAME_GLIDE,
		MINIGAME_BIKE,

		MINIGAME_END
	};
}